[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=5

#串口
serial_port="COM3"
#mqtt server  
mqtt_server="tcp://115.28.230.100:11883"
mqtt_username="terminal"
mqtt_password="000000"
forum_username="span42"
device_uuid="0000000000"
#数据是否本地存档
is_log=false
# http port
http_port=8080


#地理位置
longitude=116.403406
latitude=39.999374

